package com.xworkz.extend;

public class Quasar extends QuasarParent {

    @Override
    void category() {
        System.out.println("Overridden: Quasars are ultra-bright galactic centers powered by supermassive black holes.");
    }

    @Override
    void quasarEnergySource() {
        System.out.println("Overridden: Their immense energy is generated by matter heating up as it spirals into a supermassive black hole.");
    }

    @Override
    void brightestQuasar() {
        System.out.println("Overridden: 3C 273, located in the Virgo constellation, is the brightest and first identified quasar.");
    }

    @Override
    void quasarRedshift() {
        System.out.println("Overridden: The high redshift of quasars reveals that they are among the most distant objects in the universe.");
    }

    @Override
    void quasarDiscovery() {
        System.out.println("Overridden: Quasars were discovered in 1963 by Maarten Schmidt using spectroscopic analysis of 3C 273.");
    }
}
