class Main
{
	public static void main(String[] args)
	{
		System.out.println("Star**************");
		Star star = new Star();
		star.number=1;
		star.name="Polaris";
		star.colour="White";
		star.shapes='O';
		System.out.println("Number of Stars: "+star.number);
		System.out.println("Star Name: "+star.name);
		System.out.println("Star Colour: "+star.colour);
		System.out.println("Star shape: "+star.shapes);
		System.out.println();
		System.out.println("Updated Information:");
		Star star1= new Star();
		star1.number = 2;
		star1.name="Canis Major";
		star1.colour="Red";
		star1.shapes='A';
		System.out.println("Number of Stars: "+star1.number);
		System.out.println("Star Name: "+star1.name);
		System.out.println("Star Colour: "+star1.colour);
		System.out.println("Star Shape: "+star1.shapes);
		System.out.println();
		System.out.println("Updated Information.");
		Star star2 = new Star();
		star2.number = 45;
		star2.name="Aquila";
		star2.colour="Black";
		star2.shapes='c';
		System.out.println("Number of Stars: "+star2.number);
		System.out.println("Star Name: "+star2.name);
		System.out.println("Star Colour: "+star2.colour);
		System.out.println("Star Shape: "+star2.shapes);
		System.out.println();
		System.out.println("Updated Information!");
		Star star3 = new Star();
		star3.number=4;
		star3.name="Jupiter";
		star3.colour="Yellow";
		star3.shapes='D';
		System.out.println("Number of Stars: "+star3.number);
		System.out.println("Star Name: "+star3.name);
		System.out.println("Star Colour: "+star3.colour);
		System.out.println("Star Shapes: "+star3.shapes);
		System.out.println();
		System.out.println("Updated Information.");
		Star star4 = new Star();
		star4.number=5;
		star4.name="Mars";
		star4.colour="Orange";
		star4.shapes='E';
		System.out.println("Number Of stars: "+star4.number);
		System.out.println("Star Name: "+star4.name);
		System.out.println("Star Colour: "+star4.colour);
		System.out.println("Star Shapes: "+star4.shapes);
		System.out.println();
		System.out.println("Updated Information!");
		Star star5 = new Star();
		star5.number=54;
		star5.name="Venaus";
		star5.colour="Purple";
		star5.shapes='F';
		System.out.println("Number Of Stars: "+star5.number);
		System.out.println("Star Name: "+star5.name);
		System.out.println("Star Colour: "+star5.colour);
		System.out.println("Star Shapes: "+star.shapes);
		System.out.println();
		System.out.println("<Updated Information>");
		Star star6 = new Star();
		star6.number=7;
		star6.name="Sattran";
		star6.colour="Green";
		star6.shapes='G';
		System.out.println("Number of stars: "+star6.number);
		System.out.println("Star Name: "+star6.name);
		System.out.println("Star colour: "+star6.colour);
		System.out.println("Star shapes: "+star6.shapes);
		System.out.println();
		System.out.println("Updated Information..,.");
		Star star7 = new Star();
		star7.number=78;
		star7.name="Algol";
		star7.colour="Orange";
		star7.shapes='H';
		System.out.println("Number of stars: "+star7.number);
		System.out.println("Star Name: "+star7.name);
		System.out.println("Star Colour: "+star7.colour);
		System.out.println("Star Shapes: "+star7.shapes);
		System.out.println();
		System.out.println("Updated Information.");
		Star star8 = new Star();
		star8.number=54;
		star8.name="Xi Andromedae";
		star8.colour="Vilote";
		star8.shapes='I';
		System.out.println("Number of stars: "+star8.number);
		System.out.println("Star name: "+star8.name);
		System.out.println("Star Colours: "+star8.colour);
		System.out.println("Star Shapes: "+star8.shapes);
		System.out.println();
		System.out.println("Updated Information!");
		Star star9 = new Star();
		star9.number=16;
		star9.name="Arcturus";
		star9.colour="Blue";
		star9.shapes='J';
		System.out.println("Number of stars in the Sky: "+star9.number);
		System.out.println("Star Name: "+star9.name);
		System.out.println("Star Shapes: "+star9.shapes);
		System.out.println("Star Colour: "+star9.colour);
		System.out.println();
		System.out.println("Star End!@#$%^&*()");
		System.out.println("Bag Details!!");
		Bag bag2 = new Bag();
		bag2.price=4500;
		bag2.Company="American Tourist";
		bag2.size='M';
		bag2.colour="Black";
		System.out.println("Bag Price: "+bag2.price);
		System.out.println("Bag Company: "+bag2.Company);
		System.out.println("Bag Size: "+bag2.size);
		System.out.println("Bag Colour: "+bag2.colour);
		System.out.println();
		System.out.println("Updated Information:");
		Bag bag3 = new Bag();
		bag3.price=5000;
		bag3.Company="Sky Bags";
		bag3.size='L';
		bag3.colour="Red";
		System.out.println("Bag Price: "+bag3.price);
		System.out.println("Bag Company: "+bag3.Company);
		System.out.println("Bag Size: "+bag3.size);
		System.out.println("Bag Colour: "+bag3.colour);
		System.out.println();
		System.out.println("Updated Information:");
		Bag bag4 = new Bag();
		bag4.price=7500;
		bag4.Company="A1";
		bag4.size='S';
		bag4.colour="Green";
		System.out.println("Bag Price: "+bag4.price);
		System.out.println("Bag Company: "+bag4.Company);
		System.out.println("Bag Size: "+bag4.size);
		System.out.println("Bag Colour: "+bag4.colour);
		System.out.println();
		System.out.println("Updated Information:");
		Bag bag6 = new Bag();
		bag6.price=1550;
		bag6.Company="Baggit";
		bag6.size='M';
		bag6.colour="White";
		System.out.println("Bag Price: "+bag6.price);
		System.out.println("Bag Company: "+bag6.Company);
		System.out.println("Bag Size: "+bag6.size);
		System.out.println("Bag Colour: "+bag6.colour);
		System.out.println();
		System.out.println("Updated Information:");
		Bag bag7 = new Bag();
		bag7.price=8999;
		bag7.Company="Hidesign";
		bag7.size='S';
		bag7.colour="Purple";
		System.out.println("Bag Price: "+bag7.price);
		System.out.println("Bag Company: "+bag7.Company);
		System.out.println("Bag Size: "+bag7.size);
		System.out.println("Bag Colour: "+bag7.colour);
		System.out.println();
		System.out.println("Updated Information:");
		Bag bag8 = new Bag();
		bag8.price=999;
		bag8.Company="Mulberry";
		bag8.size='M';
		bag8.colour="Green";
		System.out.println("Bag Price: "+bag8.price);
		System.out.println("Bag Company: "+bag8.Company);
		System.out.println("Bag Size: "+bag8.size);
		System.out.println("Bag Colour: "+bag8.colour);
		System.out.println();
		System.out.println("Updated Information:");
		Bag bag9 = new Bag();
		bag9.price=9949;
		bag9.Company="EDIKO";
		bag9.size='S';
		bag9.colour="White";
		System.out.println("Bag Price: "+bag9.price);
		System.out.println("Bag Company: "+bag9.Company);
		System.out.println("Bag Size: "+bag9.size);
		System.out.println("Bag Colour: "+bag9.colour);
		System.out.println();
		System.out.println("Updated Information:");
		Bag bag10 = new Bag();
		bag10.price=2999;
		bag10.Company="Loewe";
		bag10.size='L';
		bag10.colour="Blue";
		System.out.println("Bag Price: "+bag10.price);
		System.out.println("Bag Company: "+bag10.Company);
		System.out.println("Bag Size: "+bag10.size);
		System.out.println("Bag Colour: "+bag10.colour);
		System.out.println();
		System.out.println("End Bag!!!!");
		System.out.println();
		System.out.println("Metro List");
		Metro metro1 = new Metro();
		metro1.lineClour="Green";
		metro1.StationName="Rajajinagar";
		metro1.trainNumber=100;
		metro1.numberOfPassanger=50;
		System.out.println("Line Colour: "+metro1.lineClour);
		System.out.println("Metro Station Name: "+metro1.StationName);
		System.out.println("Train Number: "+metro1.trainNumber);
		System.out.println("Number Of Passanger: "+	metro1.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		Metro metro2 = new Metro();
		metro2.lineClour="Purple";
		metro2.StationName="Baiyyappanahalli";
		metro2.trainNumber=399;
		metro2.numberOfPassanger=45;
		System.out.println("Line Colour: "+metro2.lineClour);
		System.out.println("Metro Station Name: "+metro2.StationName);
		System.out.println("Train Number: "+metro2.trainNumber);
		System.out.println("Number Of Passanger: "+	metro2.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		metro2.lineClour="Yellow";
		metro2.StationName="Bommasandra";
		metro2.trainNumber=499;
		metro2.numberOfPassanger=55;
		System.out.println("Line Colour: "+metro2.lineClour);
		System.out.println("Metro Station Name: "+metro2.StationName);
		System.out.println("Train Number: "+metro2.trainNumber);
		System.out.println("Number Of Passanger: "+	metro2.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		System.out.println("Updated List:");
		metro2.lineClour="Blue";
		metro2.StationName="Kasturi Nagar";
		metro2.trainNumber=54;
		metro2.numberOfPassanger=44;
		System.out.println("Line Colour: "+metro2.lineClour);
		System.out.println("Metro Station Name: "+metro2.StationName);
		System.out.println("Train Number: "+metro2.trainNumber);
		System.out.println("Number Of Passanger: "+	metro2.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		metro2.lineClour="Pink";
		metro2.StationName="JP Nagar 4th Phase";
		metro2.trainNumber=50;
		metro2.numberOfPassanger=50;
		System.out.println("Line Colour: "+metro2.lineClour);
		System.out.println("Metro Station Name: "+metro2.StationName);
		System.out.println("Train Number: "+metro2.trainNumber);
		System.out.println("Number Of Passanger: "+	metro2.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		metro2.lineClour="Green";
		metro2.StationName="Iskon Temple";
		metro2.trainNumber=55;
		metro2.numberOfPassanger=60;
		System.out.println("Line Colour: "+metro2.lineClour);
		System.out.println("Metro Station Name: "+metro2.StationName);
		System.out.println("Train Number: "+metro2.trainNumber);
		System.out.println("Number Of Passanger: "+	metro2.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		metro2.lineClour="Green";
		metro2.StationName="Sandal Sop Factory";
		metro2.trainNumber=7500;
		metro2.numberOfPassanger=70;
		System.out.println("Line Colour: "+metro2.lineClour);
		System.out.println("Metro Station Name: "+metro2.StationName);
		System.out.println("Train Number: "+metro2.trainNumber);
		System.out.println("Number Of Passanger: "+	metro2.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		metro2.lineClour="Green";
		metro2.StationName="Kuvempu Road";
		metro2.trainNumber=65;
		metro2.numberOfPassanger=80;
		System.out.println("Line Colour: "+metro2.lineClour);
		System.out.println("Metro Station Name: "+metro2.StationName);
		System.out.println("Train Number: "+metro2.trainNumber);
		System.out.println("Number Of Passanger: "+	metro2.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		metro2.lineClour="Green";
		metro2.StationName="Mantri Squre";
		metro2.trainNumber=56;
		metro2.numberOfPassanger=90;
		System.out.println("Line Colour: "+metro2.lineClour);
		System.out.println("Metro Station Name: "+metro2.StationName);
		System.out.println("Train Number: "+metro2.trainNumber);
		System.out.println("Number Of Passanger: "+	metro2.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		metro2.lineClour="Green";
		metro2.StationName="Mejastaic";
		metro2.trainNumber=75;
		metro2.numberOfPassanger=100;
		System.out.println("Line Colour: "+metro2.lineClour);
		System.out.println("Metro Station Name: "+metro2.StationName);
		System.out.println("Train Number: "+metro2.trainNumber);
		System.out.println("Number Of Passanger: "+	metro2.numberOfPassanger);
		System.out.println();
		System.out.println("End Metro List:");
		System.out.println();
		System.out.println("List of Industary: ");
		Industary industary = new Industary();
		industary.name="Iron & Steel";
		industary.number=800;
		industary.location="Thirthahli";
		industary.grade='A';
		System.out.println("Industary Name: "+industary.name);
		System.out.println("Employees Working in Industary: "+industary.number);
		System.out.println("Industary Location: "+industary.location);
		System.out.println("Industary Grade: "+industary.grade);
		System.out.println();
		System.out.println("\\\\pdate Information////");
		industary.name="Soap";
		industary.number=1800;
		industary.location="Koppa";
		industary.grade='B';
		System.out.println("Industary Name: "+industary.name);
		System.out.println("Employees Working in Industary: "+industary.number);
		System.out.println("Industary Location: "+industary.location);
		System.out.println("Industary Grade: "+industary.grade);
		System.out.println();
		System.out.println("\\\\pdate Information////");
		industary.name="Textiles";
		industary.number=300;
		industary.location="Chikkapete";
		industary.grade='C';
		System.out.println("Industary Name: "+industary.name);
		System.out.println("Employees Working in Industary: "+industary.number);
		System.out.println("Industary Location: "+industary.location);
		System.out.println("Industary Grade: "+industary.grade);
		System.out.println();
		System.out.println("\\\\pdate Information////");
		industary.name="Sugar";
		industary.number=400;
		industary.location="Mandya";
		industary.grade='D';
		System.out.println("Industary Name: "+industary.name);
		System.out.println("Employees Working in Industary: "+industary.number);
		System.out.println("Industary Location: "+industary.location);
		System.out.println("Industary Grade: "+industary.grade);
		System.out.println();
		System.out.println("\\\\pdate Information////");
		industary.name="Jute";
		industary.number=500;
		industary.location="Hasan";
		industary.grade='E';
		System.out.println("Industary Name: "+industary.name);
		System.out.println("Employees Working in Industary: "+industary.number);
		System.out.println("Industary Location: "+industary.location);
		System.out.println("Industary Grade: "+industary.grade);
		System.out.println();
		System.out.println("\\\\pdate Information////");
		industary.name="Cement";
		industary.number=60;
		industary.location="Shivamogga";
		industary.grade='F';
		System.out.println("Industary Name: "+industary.name);
		System.out.println("Employees Working in Industary: "+industary.number);
		System.out.println("Industary Location: "+industary.location);
		System.out.println("Industary Grade: "+industary.grade);
		System.out.println();
		System.out.println("\\\\pdate Information////");
		industary.name="Automobiles";
		industary.number=70;
		industary.location="Chikkamaggaluru";
		industary.grade='G';
		System.out.println("Industary Name: "+industary.name);
		System.out.println("Employees Working in Industary: "+industary.number);
		System.out.println("Industary Location: "+industary.location);
		System.out.println("Industary Grade: "+industary.grade);
		System.out.println();
		System.out.println("\\\\pdate Information////");
		industary.name="Paper";
		industary.number=80;
		industary.location="Shrigeri";
		industary.grade='H';
		System.out.println("Industary Name: "+industary.name);
		System.out.println("Employees Working in Industary: "+industary.number);
		System.out.println("Industary Location: "+industary.location);
		System.out.println("Industary Grade: "+industary.grade);
		System.out.println();
		System.out.println("\\\\pdate Information////");
		industary.name="Petrochemical";
		industary.number=90;
		industary.location="Udupi";
		industary.grade='I';
		System.out.println("Industary Name: "+industary.name);
		System.out.println("Employees Working in Industary: "+industary.number);
		System.out.println("Industary Location: "+industary.location);
		System.out.println("Industary Grade: "+industary.grade);
		System.out.println();
		System.out.println("\\\\pdate Information////");
		industary.name="Information Technology (IT)";
		industary.number=100;
		industary.location="Hebri";
		industary.grade='J';
		System.out.println("Industary Name: "+industary.name);
		System.out.println("Employees Working in Industary: "+industary.number);
		System.out.println("Industary Location: "+industary.location);
		System.out.println("Industary Grade: "+industary.grade);
		System.out.println();
		System.out.println("PowerBank List===");
		PowerBank powerbank = new PowerBank();
		powerbank.Company="Samsang";
		powerbank.capacity=3000;
		powerbank.colour="Black";
		powerbank.price=1000;
		System.out.println("PowerBank Company:"+powerbank.Company);
		System.out.println("PowerBank Capacity:"+powerbank.capacity+"mH");
		System.out.println("PowerBank Colour: "+powerbank.colour);
		System.out.println("PowerBank Price: "+powerbank.price);
		System.out.println();
		System.out.println("<<<<<Updated List>>>>>");
		powerbank.Company="Samsang";
		powerbank.capacity=3000;
		powerbank.colour="Black";
		powerbank.price=1000;
		System.out.println("PowerBank Company:"+powerbank.Company);
		System.out.println("PowerBank Capacity:"+powerbank.capacity+"mH");
		System.out.println("PowerBank Colour: "+powerbank.colour);
		System.out.println("PowerBank Price: "+powerbank.price);
		System.out.println();
		System.out.println("<<<<<Updated List>>>>>");
		powerbank.Company="Samsang";
		powerbank.capacity=3000;
		powerbank.colour="Black";
		powerbank.price=1000;
		System.out.println("PowerBank Company:"+powerbank.Company);
		System.out.println("PowerBank Capacity:"+powerbank.capacity+"mH");
		System.out.println("PowerBank Colour: "+powerbank.colour);
		System.out.println("PowerBank Price: "+powerbank.price);
		System.out.println();
		System.out.println("<<<<<Updated List>>>>>");
		powerbank.Company="Samsang";
		powerbank.capacity=3000;
		powerbank.colour="Black";
		powerbank.price=1000;
		System.out.println("PowerBank Company:"+powerbank.Company);
		System.out.println("PowerBank Capacity:"+powerbank.capacity+"mH");
		System.out.println("PowerBank Colour: "+powerbank.colour);
		System.out.println("PowerBank Price: "+powerbank.price);
		System.out.println();
		System.out.println("<<<<<Updated List>>>>>");
		powerbank.Company="Samsang";
		powerbank.capacity=3000;
		powerbank.colour="Black";
		powerbank.price=1000;
		System.out.println("PowerBank Company:"+powerbank.Company);
		System.out.println("PowerBank Capacity:"+powerbank.capacity+"mH");
		System.out.println("PowerBank Colour: "+powerbank.colour);
		System.out.println("PowerBank Price: "+powerbank.price);
		System.out.println();
		System.out.println("<<<<<Updated List>>>>>");
		powerbank.Company="Samsang";
		powerbank.capacity=3000;
		powerbank.colour="Black";
		powerbank.price=1000;
		System.out.println("PowerBank Company:"+powerbank.Company);
		System.out.println("PowerBank Capacity:"+powerbank.capacity+"mH");
		System.out.println("PowerBank Colour: "+powerbank.colour);
		System.out.println("PowerBank Price: "+powerbank.price);
		System.out.println();
		System.out.println("<<<<<Updated List>>>>>");
		powerbank.Company="Samsang";
		powerbank.capacity=3000;
		powerbank.colour="Black";
		powerbank.price=1000;
		System.out.println("PowerBank Company:"+powerbank.Company);
		System.out.println("PowerBank Capacity:"+powerbank.capacity+"mH");
		System.out.println("PowerBank Colour: "+powerbank.colour);
		System.out.println("PowerBank Price: "+powerbank.price);
		System.out.println();
		System.out.println("<<<<<Updated List>>>>>");
		powerbank.Company="Samsang";
		powerbank.capacity=3000;
		powerbank.colour="Black";
		powerbank.price=1000;
		System.out.println("PowerBank Company:"+powerbank.Company);
		System.out.println("PowerBank Capacity:"+powerbank.capacity+"mH");
		System.out.println("PowerBank Colour: "+powerbank.colour);
		System.out.println("PowerBank Price: "+powerbank.price);
		System.out.println();
		System.out.println("<<<<<Updated List>>>>>");
		powerbank.Company="Samsang";
		powerbank.capacity=3000;
		powerbank.colour="Black";
		powerbank.price=1000;
		System.out.println("PowerBank Company:"+powerbank.Company);
		System.out.println("PowerBank Capacity:"+powerbank.capacity+"mH");
		System.out.println("PowerBank Colour: "+powerbank.colour);
		System.out.println("PowerBank Price: "+powerbank.price);
		System.out.println();
		System.out.println("<<<<<Updated List>>>>>");
		powerbank.Company="MI";
		powerbank.capacity=3800;
		powerbank.colour="Blue";
		powerbank.price=2000;
		System.out.println("PowerBank Company:"+powerbank.Company);
		System.out.println("PowerBank Capacity:"+powerbank.capacity+"mH");
		System.out.println("PowerBank Colour: "+powerbank.colour);
		System.out.println("PowerBank Price: "+powerbank.price);
		System.out.println();
		System.out.println("<<<<<Updated List>>>>>");
		System.out.println("Bottle List:");
		Bottle bottle = new Bottle();
		bottle.size=5;
		bottle.name="Tupperware";
		bottle.colour="Blue";
		bottle.capacity=2;
		System.out.println("Bottle Size: "+bottle.size+"cm");
		System.out.println("Bottle Name: "+bottle.name);
		System.out.println("Bottle Colour: "+bottle.colour);
		System.out.println("Bottle Capicity: "+bottle.capacity+"L");
		System.out.println();
		System.out.println("Updated List:");
		bottle.size=5;
		bottle.name="Tupperware";
		bottle.colour="Blue";
		bottle.capacity=2;
		System.out.println("Bottle Size: "+bottle.size+"cm");
		System.out.println("Bottle Name: "+bottle.name);
		System.out.println("Bottle Colour: "+bottle.colour);
		System.out.println("Bottle Capicity: "+bottle.capacity+"L");
		System.out.println();
		System.out.println("Updated List:");
		bottle.size=5;
		bottle.name="Tupperware";
		bottle.colour="Blue";
		bottle.capacity=2;
		System.out.println("Bottle Size: "+bottle.size+"cm");
		System.out.println("Bottle Name: "+bottle.name);
		System.out.println("Bottle Colour: "+bottle.colour);
		System.out.println("Bottle Capicity: "+bottle.capacity+"L");
		System.out.println();
		System.out.println("Updated List:");
		bottle.size=5;
		bottle.name="Tupperware";
		bottle.colour="Blue";
		bottle.capacity=2;
		System.out.println("Bottle Size: "+bottle.size+"cm");
		System.out.println("Bottle Name: "+bottle.name);
		System.out.println("Bottle Colour: "+bottle.colour);
		System.out.println("Bottle Capicity: "+bottle.capacity+"L");
		System.out.println();
		System.out.println("Updated List:");
		bottle.size=5;
		bottle.name="Tupperware";
		bottle.colour="Blue";
		bottle.capacity=2;
		System.out.println("Bottle Size: "+bottle.size+"cm");
		System.out.println("Bottle Name: "+bottle.name);
		System.out.println("Bottle Colour: "+bottle.colour);
		System.out.println("Bottle Capicity: "+bottle.capacity+"L");
		System.out.println();
		System.out.println("Updated List:");
		bottle.size=5;
		bottle.name="Tupperware";
		bottle.colour="Blue";
		bottle.capacity=2;
		System.out.println("Bottle Size: "+bottle.size+"cm");
		System.out.println("Bottle Name: "+bottle.name);
		System.out.println("Bottle Colour: "+bottle.colour);
		System.out.println("Bottle Capicity: "+bottle.capacity+"L");
		System.out.println();
		System.out.println("Updated List:");
		bottle.size=6;
		bottle.name="Fanta";
		bottle.colour="Orange";
		bottle.capacity=2;
		System.out.println("Bottle Size: "+bottle.size+"cm");
		System.out.println("Bottle Name: "+bottle.name);
		System.out.println("Bottle Colour: "+bottle.colour);
		System.out.println("Bottle Capicity: "+bottle.capacity+"L");
		System.out.println();
		System.out.println("Updated List:");
		bottle.size=4;
		bottle.name="Glass";
		bottle.colour="Yellow";
		bottle.capacity=7;
		System.out.println("Bottle Size: "+bottle.size+"cm");
		System.out.println("Bottle Name: "+bottle.name);
		System.out.println("Bottle Colour: "+bottle.colour);
		System.out.println("Bottle Capicity: "+bottle.capacity+"L");
		System.out.println();
		System.out.println("Updated List:");
		bottle.size=1;
		bottle.name="Celloo";
		bottle.colour="White";
		bottle.capacity=3;
		System.out.println("Bottle Size: "+bottle.size+"cm");
		System.out.println("Bottle Name: "+bottle.name);
		System.out.println("Bottle Colour: "+bottle.colour);
		System.out.println("Bottle Capicity: "+bottle.capacity+"L");
		System.out.println();
		System.out.println("Updated List:");
		bottle.size=4;
		bottle.name="Pexpo";
		bottle.colour="Purple";
		bottle.capacity=1;
		System.out.println("Bottle Size: "+bottle.size+"cm");
		System.out.println("Bottle Name: "+bottle.name);
		System.out.println("Bottle Colour: "+bottle.colour);
		System.out.println("Bottle Capicity: "+bottle.capacity+"L");
		System.out.println();
		System.out.println("Bottle List End:");
		System.out.println();
		System.out.println("Lamp List:");
		Lamp lamp = new Lamp();
		lamp.colour="Red";
		lamp.size=4;
		lamp.light="Red";
		lamp.grade='A';
		System.out.println("Lamp Colour: "+lamp.colour);
		System.out.println("Lamp Size: "+lamp.size+"cm");
		System.out.println("Lamp Light Colour: "+lamp.light);
		System.out.println("Lamp Grade: "+lamp.grade);
		System.out.println();
		System.out.println("Update List:");
		lamp.colour="Red";
		lamp.size=4;
		lamp.light="Red";
		lamp.grade='A';
		System.out.println("Lamp Colour: "+lamp.colour);
		System.out.println("Lamp Size: "+lamp.size+"cm");
		System.out.println("Lamp Light Colour: "+lamp.light);
		System.out.println("Lamp Grade: "+lamp.grade);
		System.out.println();
		System.out.println("Update List:");
		lamp.colour="Red";
		lamp.size=4;
		lamp.light="Red";
		lamp.grade='A';
		System.out.println("Lamp Colour: "+lamp.colour);
		System.out.println("Lamp Size: "+lamp.size+"cm");
		System.out.println("Lamp Light Colour: "+lamp.light);
		System.out.println("Lamp Grade: "+lamp.grade);
		System.out.println();
		System.out.println("Update List:");
		lamp.colour="Red";
		lamp.size=4;
		lamp.light="Red";
		lamp.grade='A';
		System.out.println("Lamp Colour: "+lamp.colour);
		System.out.println("Lamp Size: "+lamp.size+"cm");
		System.out.println("Lamp Light Colour: "+lamp.light);
		System.out.println("Lamp Grade: "+lamp.grade);
		System.out.println();
		System.out.println("Update List:");
		lamp.colour="Red";
		lamp.size=4;
		lamp.light="Red";
		lamp.grade='A';
		System.out.println("Lamp Colour: "+lamp.colour);
		System.out.println("Lamp Size: "+lamp.size+"cm");
		System.out.println("Lamp Light Colour: "+lamp.light);
		System.out.println("Lamp Grade: "+lamp.grade);
		System.out.println();
		System.out.println("Update List:");
		lamp.colour="Red";
		lamp.size=4;
		lamp.light="Red";
		lamp.grade='A';
		System.out.println("Lamp Colour: "+lamp.colour);
		System.out.println("Lamp Size: "+lamp.size+"cm");
		System.out.println("Lamp Light Colour: "+lamp.light);
		System.out.println("Lamp Grade: "+lamp.grade);
		System.out.println();
		System.out.println("Update List:");
		lamp.colour="Red";
		lamp.size=4;
		lamp.light="Red";
		lamp.grade='A';
		System.out.println("Lamp Colour: "+lamp.colour);
		System.out.println("Lamp Size: "+lamp.size+"cm");
		System.out.println("Lamp Light Colour: "+lamp.light);
		System.out.println("Lamp Grade: "+lamp.grade);
		System.out.println();
		System.out.println("Update List:");
		lamp.colour="Red";
		lamp.size=4;
		lamp.light="Red";
		lamp.grade='A';
		System.out.println("Lamp Colour: "+lamp.colour);
		System.out.println("Lamp Size: "+lamp.size+"cm");
		System.out.println("Lamp Light Colour: "+lamp.light);
		System.out.println("Lamp Grade: "+lamp.grade);
		System.out.println();
		System.out.println("Update List:");
		lamp.colour="Red";
		lamp.size=4;
		lamp.light="Red";
		lamp.grade='A';
		System.out.println("Lamp Colour: "+lamp.colour);
		System.out.println("Lamp Size: "+lamp.size+"cm");
		System.out.println("Lamp Light Colour: "+lamp.light);
		System.out.println("Lamp Grade: "+lamp.grade);
		System.out.println();
		System.out.println("Update List:");
		lamp.colour="Red";
		lamp.size=4;
		lamp.light="Red";
		lamp.grade='A';
		System.out.println("Lamp Colour: "+lamp.colour);
		System.out.println("Lamp Size: "+lamp.size+"cm");
		System.out.println("Lamp Light Colour: "+lamp.light);
		System.out.println("Lamp Grade: "+lamp.grade);
		System.out.println();
		System.out.println("Update List:");
		lamp.colour="Blue";
		lamp.size=7;
		lamp.light="Red";
		lamp.grade='k';
		System.out.println("Lamp Colour: "+lamp.colour);
		System.out.println("Lamp Size: "+lamp.size+"cm");
		System.out.println("Lamp Light Colour: "+lamp.light);
		System.out.println("Lamp Grade: "+lamp.grade);
		System.out.println();
		System.out.println("Lamp List End:");
		System.out.println("Earth List:");
		Earth earth = new Earth();
		earth.colour="Blue";
		earth.size=1000;
		earth.shape="rodun";
		earth.space=1000;
		System.out.println("Earth Colour: "+earth.colour);
		System.out.println("Earth Size: "+earth.size);
		System.out.println("Earth Shape: "+earth.shape);
		System.out.println("Earth Space: "+earth.space);
		System.out.println();
		System.out.println("Bullete List:");
		Bullet bullet = new Bullet();
		bullet.size=40;
		bullet.name="Bullet";
		bullet.grade='A';
		bullet.speed=7000;
		System.out.println("Bullet Size: "+bullet.size);
		System.out.println("Bullete Name: "+bullet.name);
		System.out.println("Bullet Grade: "+bullet.grade);
		System.out.println("Bullet Speed: "+bullet.speed);
		System.out.println();
		System.out.println("Update List:");
		bullet.size=40;
		bullet.name="Bullet";
		bullet.grade='A';
		bullet.speed=7000;
		System.out.println("Bullet Size: "+bullet.size);
		System.out.println("Bullete Name: "+bullet.name);
		System.out.println("Bullet Grade: "+bullet.grade);
		System.out.println("Bullet Speed: "+bullet.speed);
		System.out.println();
		System.out.println("Update List:");
		bullet.size=40;
		bullet.name="Bullet";
		bullet.grade='A';
		bullet.speed=7000;
		System.out.println("Bullet Size: "+bullet.size);
		System.out.println("Bullete Name: "+bullet.name);
		System.out.println("Bullet Grade: "+bullet.grade);
		System.out.println("Bullet Speed: "+bullet.speed);
		System.out.println();
		System.out.println("Update List:");
		bullet.size=40;
		bullet.name="Bullet";
		bullet.grade='A';
		bullet.speed=7000;
		System.out.println("Bullet Size: "+bullet.size);
		System.out.println("Bullete Name: "+bullet.name);
		System.out.println("Bullet Grade: "+bullet.grade);
		System.out.println("Bullet Speed: "+bullet.speed);
		System.out.println();
		System.out.println("Update List:");
		bullet.size=40;
		bullet.name="Bullet";
		bullet.grade='A';
		bullet.speed=7000;
		System.out.println("Bullet Size: "+bullet.size);
		System.out.println("Bullete Name: "+bullet.name);
		System.out.println("Bullet Grade: "+bullet.grade);
		System.out.println("Bullet Speed: "+bullet.speed);
		System.out.println();
		System.out.println("Update List:");
		bullet.size=40;
		bullet.name="Bullet";
		bullet.grade='A';
		bullet.speed=7000;
		System.out.println("Bullet Size: "+bullet.size);
		System.out.println("Bullete Name: "+bullet.name);
		System.out.println("Bullet Grade: "+bullet.grade);
		System.out.println("Bullet Speed: "+bullet.speed);
		System.out.println();
		System.out.println("Update List:");
		bullet.size=40;
		bullet.name="Bullet";
		bullet.grade='A';
		bullet.speed=7000;
		System.out.println("Bullet Size: "+bullet.size);
		System.out.println("Bullete Name: "+bullet.name);
		System.out.println("Bullet Grade: "+bullet.grade);
		System.out.println("Bullet Speed: "+bullet.speed);
		System.out.println();
		System.out.println("Update List:");
		bullet.size=40;
		bullet.name="Bullet";
		bullet.grade='A';
		bullet.speed=7000;
		System.out.println("Bullet Size: "+bullet.size);
		System.out.println("Bullete Name: "+bullet.name);
		System.out.println("Bullet Grade: "+bullet.grade);
		System.out.println("Bullet Speed: "+bullet.speed);
		System.out.println();
		System.out.println("Update List:");
		bullet.size=40;
		bullet.name="Bullet";
		bullet.grade='A';
		bullet.speed=7000;
		System.out.println("Bullet Size: "+bullet.size);
		System.out.println("Bullete Name: "+bullet.name);
		System.out.println("Bullet Grade: "+bullet.grade);
		System.out.println("Bullet Speed: "+bullet.speed);
		System.out.println();
		System.out.println("Update List:");
		bullet.size=70;
		bullet.name="Bullet";
		bullet.grade='A';
		bullet.speed=8000;
		System.out.println("Bullet Size: "+bullet.size);
		System.out.println("Bullete Name: "+bullet.name);
		System.out.println("Bullet Grade: "+bullet.grade);
		System.out.println("Bullet Speed: "+bullet.speed);
		System.out.println();
		System.out.println("Bullet List End:");
		System.out.println();
		System.out.println("List of Flags:");
		Flag flage = new Flag();
		flage.price=5000;
		flage.Company="Sky Bags";
		flage.size='L';
		flage.colour="Red";
		System.out.println(flage.price);
		System.out.println(flage.Company);
		System.out.println(flage.size);
		System.out.println(flage.colour);
		flage.price=5000;
		flage.Company="Sky Bags";
		flage.size='L';
		flage.colour="Red";
		System.out.println(flage.price);
		System.out.println(flage.Company);
		System.out.println(flage.size);
		System.out.println(flage.colour);
		flage.price=5000;
		flage.Company="Sky Bags";
		flage.size='L';
		flage.colour="Red";
		System.out.println(flage.price);
		System.out.println(flage.Company);
		System.out.println(flage.size);
		System.out.println(flage.colour);
		flage.price=5000;
		flage.Company="Sky Bags";
		flage.size='L';
		flage.colour="Red";
		System.out.println(flage.price);
		System.out.println(flage.Company);
		System.out.println(flage.size);
		System.out.println(flage.colour);
		flage.price=5000;
		flage.Company="Sky Bags";
		flage.size='L';
		flage.colour="Red";
		System.out.println(flage.price);
		System.out.println(flage.Company);
		System.out.println(flage.size);
		System.out.println(flage.colour);
		flage.price=5000;
		flage.Company="Sky Bags";
		flage.size='L';
		flage.colour="Red";
		System.out.println(flage.price);
		System.out.println(flage.Company);
		System.out.println(flage.size);
		System.out.println(flage.colour);
		flage.price=5000;
		flage.Company="Sky Bags";
		flage.size='L';
		flage.colour="Red";
		System.out.println(flage.price);
		System.out.println(flage.Company);
		System.out.println(flage.size);
		System.out.println(flage.colour);
		flage.price=5000;
		flage.Company="Sky Bags";
		flage.size='L';
		flage.colour="Red";
		System.out.println(flage.price);
		System.out.println(flage.Company);
		System.out.println(flage.size);
		System.out.println(flage.colour);
		flage.price=5000;
		flage.Company="Sky Bags";
		flage.size='L';
		flage.colour="Red";
		System.out.println(flage.price);
		System.out.println(flage.Company);
		System.out.println(flage.size);
		System.out.println(flage.colour);
		flage.price=5000;
		flage.Company="Sky Bags";
		flage.size='L';
		flage.colour="Red";
		System.out.println(flage.price);
		System.out.println(flage.Company);
		System.out.println(flage.size);
		System.out.println(flage.colour);
		flage.price=5000;
		flage.Company="Sky Bags";
		flage.size='L';
		flage.colour="Red";
		System.out.println(flage.price);
		System.out.println(flage.Company);
		System.out.println(flage.size);
		System.out.println(flage.colour);
		System.out.println("End List:");
		System.out.println();
		System.out.println("Chocalate List:");
		Chocalate chocalate = new Chocalate();
		chocalate.name="Diray Milk";
		chocalate.price=100;
		chocalate.size="M";
		chocalate.grade='A';
		System.out.println(chocalate.name);
		System.out.println(chocalate.size);
		System.out.println(chocalate.price);
		System.out.println(chocalate.grade);
		System.out.println();
		chocalate.name="Diray Milk";
		chocalate.price=100;
		chocalate.size="M";
		chocalate.grade='A';
		System.out.println(chocalate.name);
		System.out.println(chocalate.size);
		System.out.println(chocalate.price);
		System.out.println(chocalate.grade);
		System.out.println();
		chocalate.name="Diray Milk";
		chocalate.price=100;
		chocalate.size="M";
		chocalate.grade='A';
		System.out.println(chocalate.name);
		System.out.println(chocalate.size);
		System.out.println(chocalate.price);
		System.out.println(chocalate.grade);
		System.out.println();
		
		chocalate.name="Diray Milk";
		chocalate.price=100;
		chocalate.size="M";
		chocalate.grade='A';
		System.out.println(chocalate.name);
		System.out.println(chocalate.size);
		System.out.println(chocalate.price);
		System.out.println(chocalate.grade);
		System.out.println();
		
		chocalate.name="Diray Milk";
		chocalate.price=100;
		chocalate.size="M";
		chocalate.grade='A';
		System.out.println(chocalate.name);
		System.out.println(chocalate.size);
		System.out.println(chocalate.price);
		System.out.println(chocalate.grade);
		System.out.println();
		
		chocalate.name="Diray Milk";
		chocalate.price=100;
		chocalate.size="M";
		chocalate.grade='A';
		System.out.println(chocalate.name);
		System.out.println(chocalate.size);
		System.out.println(chocalate.price);
		System.out.println(chocalate.grade);
		System.out.println();
		
		chocalate.name="Diray Milk";
		chocalate.price=100;
		chocalate.size="M";
		chocalate.grade='A';
		System.out.println(chocalate.name);
		System.out.println(chocalate.size);
		System.out.println(chocalate.price);
		System.out.println(chocalate.grade);
		System.out.println();
		
		chocalate.name="Diray Milk";
		chocalate.price=100;
		chocalate.size="M";
		chocalate.grade='A';
		System.out.println(chocalate.name);
		System.out.println(chocalate.size);
		System.out.println(chocalate.price);
		System.out.println(chocalate.grade);
		System.out.println();
		
		chocalate.name="Diray Milk";
		chocalate.price=100;
		chocalate.size="M";
		chocalate.grade='A';
		System.out.println(chocalate.name);
		System.out.println(chocalate.size);
		System.out.println(chocalate.price);
		System.out.println(chocalate.grade);
		System.out.println();
		
		chocalate.name="Milky Bar";
		chocalate.price=10;
		chocalate.size="M";
		chocalate.grade='A';
		System.out.println(chocalate.name);
		System.out.println(chocalate.size);
		System.out.println(chocalate.price);
		System.out.println(chocalate.grade);
		System.out.println();
		System.out.println("Cambra Details List:");
		Cambra cambra = new Cambra();
		cambra.name="Nikon";
		cambra.size=100;
		cambra.lens="Short Lense";
		cambra.colour="Black";
		System.out.println("Cambra Name: "+cambra.name);
		System.out.println("Cambra Size: "+cambra.size);
		System.out.println("Cambra Lense: "+cambra.lens);
		System.out.println("Cambra Colour: "+cambra.colour);
		System.out.println();
		System.out.println("Updated List>");
		cambra.name="Nikon";
		cambra.size=100;
		cambra.lens="Short Lense";
		cambra.colour="Black";
		System.out.println("Cambra Name: "+cambra.name);
		System.out.println("Cambra Size: "+cambra.size);
		System.out.println("Cambra Lense: "+cambra.lens);
		System.out.println("Cambra Colour: "+cambra.colour);
		System.out.println();
		System.out.println("Updated List>");
		cambra.name="Nikon";
		cambra.size=100;
		cambra.lens="Short Lense";
		cambra.colour="Black";
		System.out.println("Cambra Name: "+cambra.name);
		System.out.println("Cambra Size: "+cambra.size);
		System.out.println("Cambra Lense: "+cambra.lens);
		System.out.println("Cambra Colour: "+cambra.colour);
		System.out.println();
		System.out.println("Updated List>");
		cambra.name="Nikon";
		cambra.size=100;
		cambra.lens="Short Lense";
		cambra.colour="Black";
		System.out.println("Cambra Name: "+cambra.name);
		System.out.println("Cambra Size: "+cambra.size);
		System.out.println("Cambra Lense: "+cambra.lens);
		System.out.println("Cambra Colour: "+cambra.colour);
		System.out.println();
		System.out.println("Updated List>");
		cambra.name="Nikon";
		cambra.size=100;
		cambra.lens="Short Lense";
		cambra.colour="Black";
		System.out.println("Cambra Name: "+cambra.name);
		System.out.println("Cambra Size: "+cambra.size);
		System.out.println("Cambra Lense: "+cambra.lens);
		System.out.println("Cambra Colour: "+cambra.colour);
		System.out.println();
		System.out.println("Updated List>");
		cambra.name="Nikon";
		cambra.size=100;
		cambra.lens="Short Lense";
		cambra.colour="Black";
		System.out.println("Cambra Name: "+cambra.name);
		System.out.println("Cambra Size: "+cambra.size);
		System.out.println("Cambra Lense: "+cambra.lens);
		System.out.println("Cambra Colour: "+cambra.colour);
		System.out.println();
		System.out.println("Updated List>");
		cambra.name="Nikon";
		cambra.size=100;
		cambra.lens="Short Lense";
		cambra.colour="Black";
		System.out.println("Cambra Name: "+cambra.name);
		System.out.println("Cambra Size: "+cambra.size);
		System.out.println("Cambra Lense: "+cambra.lens);
		System.out.println("Cambra Colour: "+cambra.colour);
		System.out.println();
		System.out.println("Updated List>");
		cambra.name="Nikon";
		cambra.size=100;
		cambra.lens="Short Lense";
		cambra.colour="Black";
		System.out.println("Cambra Name: "+cambra.name);
		System.out.println("Cambra Size: "+cambra.size);
		System.out.println("Cambra Lense: "+cambra.lens);
		System.out.println("Cambra Colour: "+cambra.colour);
		System.out.println();
		System.out.println("Updated List>");
		cambra.name="Nikon";
		cambra.size=100;
		cambra.lens="Short Lense";
		cambra.colour="Black";
		System.out.println("Cambra Name: "+cambra.name);
		System.out.println("Cambra Size: "+cambra.size);
		System.out.println("Cambra Lense: "+cambra.lens);
		System.out.println("Cambra Colour: "+cambra.colour);
		System.out.println();
		System.out.println("Updated List>");
		cambra.name="Canon";
		cambra.size=400;
		cambra.lens="Long Lense";
		cambra.colour="White";
		System.out.println("Cambra Name: "+cambra.name);
		System.out.println("Cambra Size: "+cambra.size);
		System.out.println("Cambra Lense: "+cambra.lens);
		System.out.println("Cambra Colour: "+cambra.colour);
		System.out.println();
		System.out.println("End Cambra List>");
		System.out.println();
		System.out.println(":::Train List:::");
		Train train = new Train();
		train.lineClour="Green";
		train.StationName="Iskon Temple";
		train.trainNumber=55;
		train.numberOfPassanger=60;
		System.out.println("Line Colour: "+train.lineClour);
		System.out.println("Metro Station Name: "+train.StationName);
		System.out.println("Train Number: "+train.trainNumber);
		System.out.println("Number Of Passanger: "+	train.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		train.lineClour="Green";
		train.StationName="Iskon Temple";
		train.trainNumber=55;
		train.numberOfPassanger=60;
		System.out.println("Line Colour: "+train.lineClour);
		System.out.println("Metro Station Name: "+train.StationName);
		System.out.println("Train Number: "+train.trainNumber);
		System.out.println("Number Of Passanger: "+	train.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		train.lineClour="Green";
		train.StationName="Iskon Temple";
		train.trainNumber=55;
		train.numberOfPassanger=60;
		System.out.println("Line Colour: "+train.lineClour);
		System.out.println("Metro Station Name: "+train.StationName);
		System.out.println("Train Number: "+train.trainNumber);
		System.out.println("Number Of Passanger: "+	train.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		train.lineClour="Green";
		train.StationName="Iskon Temple";
		train.trainNumber=55;
		train.numberOfPassanger=60;
		System.out.println("Line Colour: "+train.lineClour);
		System.out.println("Metro Station Name: "+train.StationName);
		System.out.println("Train Number: "+train.trainNumber);
		System.out.println("Number Of Passanger: "+	train.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		train.lineClour="Green";
		train.StationName="Iskon Temple";
		train.trainNumber=55;
		train.numberOfPassanger=60;
		System.out.println("Line Colour: "+train.lineClour);
		System.out.println("Metro Station Name: "+train.StationName);
		System.out.println("Train Number: "+train.trainNumber);
		System.out.println("Number Of Passanger: "+	train.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		train.lineClour="Green";
		train.StationName="Iskon Temple";
		train.trainNumber=55;
		train.numberOfPassanger=60;
		System.out.println("Line Colour: "+train.lineClour);
		System.out.println("Metro Station Name: "+train.StationName);
		System.out.println("Train Number: "+train.trainNumber);
		System.out.println("Number Of Passanger: "+	train.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		train.lineClour="Green";
		train.StationName="Iskon Temple";
		train.trainNumber=55;
		train.numberOfPassanger=60;
		System.out.println("Line Colour: "+train.lineClour);
		System.out.println("Metro Station Name: "+train.StationName);
		System.out.println("Train Number: "+train.trainNumber);
		System.out.println("Number Of Passanger: "+	train.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		train.lineClour="Green";
		train.StationName="Iskon Temple";
		train.trainNumber=55;
		train.numberOfPassanger=60;
		System.out.println("Line Colour: "+train.lineClour);
		System.out.println("Metro Station Name: "+train.StationName);
		System.out.println("Train Number: "+train.trainNumber);
		System.out.println("Number Of Passanger: "+	train.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		train.lineClour="Green";
		train.StationName="Iskon Temple";
		train.trainNumber=55;
		train.numberOfPassanger=60;
		System.out.println("Line Colour: "+train.lineClour);
		System.out.println("Metro Station Name: "+train.StationName);
		System.out.println("Train Number: "+train.trainNumber);
		System.out.println("Number Of Passanger: "+	train.numberOfPassanger);
		System.out.println();
		System.out.println("Updated List:");
		train.lineClour="Red";
		train.StationName="Shivamogga";
		train.trainNumber=50;
		train.numberOfPassanger=100;
		System.out.println("Line Colour: "+train.lineClour);
		System.out.println("Metro Station Name: "+train.StationName);
		System.out.println("Train Number: "+train.trainNumber);
		System.out.println("Number Of Passanger: "+	train.numberOfPassanger);
		System.out.println();
		System.out.println("Train List End:");
		System.out.println();
		System.out.println("/-/-/Road List/-/-/");
		Road road = new Road();
		road.name="Double Road";
		road.km=100;
		road.size=40;
		road.type="Stright Road";
		System.out.println("Road Name :"+road.name);
		System.out.println("Road KM:"+road.km);
		System.out.println("Road Size:"+road.size+"m");
		System.out.println("Road Type:"+road.type);
		System.out.println();
		System.out.println("Updated List::");
		road.name="Double Road";
		road.km=100;
		road.size=40;
		road.type="Stright Road";
		System.out.println("Road Name :"+road.name);
		System.out.println("Road KM:"+road.km);
		System.out.println("Road Size:"+road.size+"m");
		System.out.println("Road Type:"+road.type);
		System.out.println();
		System.out.println("Updated List::");
		road.name="Double Road";
		road.km=100;
		road.size=40;
		road.type="Stright Road";
		System.out.println("Road Name :"+road.name);
		System.out.println("Road KM:"+road.km);
		System.out.println("Road Size:"+road.size+"m");
		System.out.println("Road Type:"+road.type);
		System.out.println();
		System.out.println("Updated List::");
		road.name="Double Road";
		road.km=100;
		road.size=40;
		road.type="Stright Road";
		System.out.println("Road Name :"+road.name);
		System.out.println("Road KM:"+road.km);
		System.out.println("Road Size:"+road.size+"m");
		System.out.println("Road Type:"+road.type);
		System.out.println();
		System.out.println("Updated List::");
		road.name="Double Road";
		road.km=100;
		road.size=40;
		road.type="Stright Road";
		System.out.println("Road Name :"+road.name);
		System.out.println("Road KM:"+road.km);
		System.out.println("Road Size:"+road.size+"m");
		System.out.println("Road Type:"+road.type);
		System.out.println();
		System.out.println("Updated List::");
		road.name="Double Road";
		road.km=100;
		road.size=40;
		road.type="Stright Road";
		System.out.println("Road Name :"+road.name);
		System.out.println("Road KM:"+road.km);
		System.out.println("Road Size:"+road.size+"m");
		System.out.println("Road Type:"+road.type);
		System.out.println();
		System.out.println("Updated List::");
		road.name="Double Road";
		road.km=100;
		road.size=40;
		road.type="Stright Road";
		System.out.println("Road Name :"+road.name);
		System.out.println("Road KM:"+road.km);
		System.out.println("Road Size:"+road.size+"m");
		System.out.println("Road Type:"+road.type);
		System.out.println();
		System.out.println("Updated List::");
		road.name="Double Road";
		road.km=100;
		road.size=40;
		road.type="Stright Road";
		System.out.println("Road Name :"+road.name);
		System.out.println("Road KM:"+road.km);
		System.out.println("Road Size:"+road.size+"m");
		System.out.println("Road Type:"+road.type);
		System.out.println();
		System.out.println("Updated List::");
		road.name="Double Road";
		road.km=100;
		road.size=40;
		road.type="Stright Road";
		System.out.println("Road Name :"+road.name);
		System.out.println("Road KM:"+road.km);
		System.out.println("Road Size:"+road.size+"m");
		System.out.println("Road Type:"+road.type);
		System.out.println();
		System.out.println("Updated List::");
		road.name="CK Road";
		road.km=800;
		road.size=70;
		road.type="Single Road";
		System.out.println("Road Name :"+road.name);
		System.out.println("Road KM:"+road.km);
		System.out.println("Road Size:"+road.size+"m");
		System.out.println("Road Type:"+road.type);
		System.out.println();
		System.out.println("Updated List::");
		road.name="KC Road";
		road.km=150;
		road.size=45;
		road.type="Curve Road";
		System.out.println("Road Name :"+road.name);
		System.out.println("Road KM:"+road.km);
		System.out.println("Road Size:"+road.size+"m");
		System.out.println("Road Type:"+road.type);
		System.out.println();
		System.out.println("Road List End::");
		System.out.println("!@#$%^&*()END!@#$%^&*()");
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		


		
		
		

	}
}