package com.xworkz.implement.Runner;

import com.xworkz.implement.Implements1.*;
import com.xworkz.implement.Interfaces.*;




public class Runner {
    public static void main(String[] args) {
        Vehicle vehicle=new VehicleImplements1();
        vehicle.behaviour();
        vehicle.identity();
        vehicle.state();
        Book book=new BookImplements1();
        book.behaviour();
        book.state();
        book.identity();
        Bottle bottle=new BottleImplements1();
        bottle.behaviour();
        bottle.state();
        bottle.identity();
        Chair chair=new ChairImplements1();
        chair.behaviour();
        chair.state();
        chair.identity();
        Fan fan=new FanImplements1();
        fan.behaviour();
        Laptop laptop=new LaptopImplements1();
        laptop.behaviour();
        Pen pen=new PenImplements1();
        pen.state();
        Smartphone smartphone=new SmartphoneImplements1();
        smartphone.state();
        Table table=new TableImplements1();
        table.behaviour();
        Television television=new TelevisionImplements1();
        television.identity();
        Fridge fridge=new FridgeImplements1();
        fridge.state();
        Car car=new CarImplements1();
        car.behaviour();
        Bike bike=new BikeImplements1();
        bike.identity();
        Bus bus=new BusImplements1();
        bus.state();
        Train train=new TrainImplements1();
        train.behaviour();
        Airplane airplane=new AirplaneImplements1();
        airplane.identity();
        Ship ship=new ShipImplements1();
        ship.state();
        Clock clock=new ClockImplements1();
        clock.behaviour();
        Watch watch=new WatchImplements1();
        watch.identity();
        Speaker speaker=new SpeakerImplements1();
        speaker.state();
        Headphone headphone=new HeadphoneImplements1();
        headphone.behaviour();
        Camera camera=new CameraImplements1();
        camera.identity();
        Bulb bulb=new BulbImplements1();
        bulb.state();
        Calculator calculator=new CalculatorImplements1();
        calculator.behaviour();
        Microwave microwave=new MicrowaveImplements1();
        microwave.identity();
        WasshingMachine wasshingMachine=new WashingMachineImplements1();
        wasshingMachine.state();
        Oven oven=new OvenImplements1();
        oven.behaviour();
        Plate plate=new PlateImplements1();
        plate.identity();
        Spoon spoon=new SpoonImplements1();
        spoon.identity();
        Cup cup=new CupImplements1();
        cup.state();
        Glass glass=new GlassImplements1();
        glass.behaviour();
        Door door=new DoorImplements1();
        door.identity();
        Window window=new WindowImplements1();
        window.state();
        Wall wall=new WallImplements1();
        wall.behaviour();
        Roof roof=new RoofImplements();
        roof.identity();
        Floor floor=new FloorImplements1();
        floor.state();
        Key key=new KeyImplements1();
        key.behaviour();
        Lock lock=new LockImplements1();
        lock.identity();
        Bag bag=new BagImplements1();
        bag.state();
        Shirt shirt=new ShirtImplements1();
        shirt.behaviour();
        Pant pant=new PantImplements1();
        pant.behaviour();
        Shoe shoe=new ShoeImplements1();
        shoe.identity();
        Socks socks=new SocksImplements1();
        socks.state();
        Cap cap=new CapImplements1();
        cap.behaviour();
        Helmet helmet=new HelmetImplements1();
        helmet.identity();
        Pillow pillow=new PillowImplements1();
        pillow.state();
        Blanket blanket=new BlanketImplements1();
        blanket.behaviour();
        Bed bed=new BedImplements1();
        bed.identity();
        Sofa sofa=new SofaImplements1();
        sofa.state();
        Carpet carpet=new CarpetImplements1();
        carpet.behaviour();
        Mirror mirror=new MirrorImplements1();
        mirror.behaviour();
        Comb comb=new CombImplemets1();
        comb.identity();
        Toothbrush toothbrush=new ToothbrushImplements1();
        toothbrush.state();
        Toothpaste toothpaste=new ToothpasteImplements1();
        toothpaste.behaviour();
        Soap soap=new SoapImplements1();
        soap.identity();
        Shampoo shampoo=new ShampooImplements1();
        shampoo.identity();
        Towel towel=new TowelImplements1();
        towel.state();
        Curtain curtain=new CurtainImplements1();
        curtain.behaviour();
        Lamp lamp=new LampImplements1();
        lamp.identity();
        Remote remote=new RemoteImplements1();
        remote.state();
        Battery battery=new BatteryImplements1();
        battery.behaviour();
        Drone drone=new DroneImplements1();
        drone.identity();
        Printer printer=new PrinterImplements1();
        printer.identity();
        Mouse mouse=new MouseImplements1();
        mouse.state();
        Keyboard keyboard=new KeyboardImplements1();
        keyboard.behaviour();
        Monitor monitor=new MonitorImplements1();
        monitor.identity();
        Projector projector=new ProjectorImplements1();
        projector.state();
        Satelite satelite=new SatelliteImplements1();
        satelite.behaviour();
        Rocket rocket=new RocketImplements1();
        rocket.identity();
        Telescope telescope=new TelescopeImplements1();
        telescope.state();
        Microscope microscope=new MicroscopeImplements1();
        microscope.behaviour();
        Screwdriver screwdriver=new ScrewdriverImplements1();
        screwdriver.identity();
        Hammer hammer=new HammerImplements1();
        hammer.identity();
        Nail nail=new NailImplements1();
        nail.state();
    }
}
