package com.xworkz.implement.Runner2;
import com.xworkz.implement.Interfaces.*;
import com.xworkz.implement.Implements2.*;


public class Runner {
    public static void main(String[] args) {
        Chair chair=new ChairImplements2();
        chair.identity();
        chair.state();
        chair.behaviour();
        Table table=new ChairImplements2();
        table.behaviour();
        table.identity();
        table.state();
        Pen pen=new PenImplements2();
        pen.state();
        pen.behaviour();
        pen.identity();
        Book book=new PenImplements2();
        book.identity();
        Laptop laptop=new LaptopImplements2();
        laptop.behaviour();
        Smartphone smartphone=new LaptopImplements2();
        smartphone.behaviour();
        Bottle bottle=new BottleImplements2();
        bottle.state();
        Fan fan=new BottleImplements2();
        fan.identity();
        Television television=new TelevisionImplements2();
        television.behaviour();
        Fridge fridge=new TelevisionImplements2();
        fridge.behaviour();
        Car car=new CarImplements2();
        car.identity();
        Bike bike=new CarImplements2();
        bike.identity();
        Bus bus=new BusImplements2();
        bus.state();
        Train train=new BusImplements2();
        train.state();
        Airplane airplane=new AirplaneImplements2();
        airplane.behaviour();
        Ship ship=new AirplaneImplements2();
        ship.behaviour();
        Clock clock=new ClockImplements2();
        clock.identity();
        Watch watch=new ClockImplements2();
        watch.identity();
        Speaker speaker=new SpeakerImplements2();
        speaker.state();
        Headphone headphone=new SpeakerImplements2();
        headphone.state();
        Camera camera=new CameraImplements2();
        camera.behaviour();
        Bulb bulb=new CameraImplements2();
        bulb.behaviour();
        Calculator calculator=new CalculatorImplements2();
        calculator.identity();
        Microwave microwave=new CalculatorImplements2();
        microwave.identity();
        WasshingMachine wasshingMachine=new WashingMachineImplements2();
        wasshingMachine.state();
        Oven oven=new WashingMachineImplements2();
        oven.state();
        Plate plate=new PlateImplements2();
        plate.behaviour();
        Spoon spoon=new PlateImplements2();
        spoon.behaviour();
        Cup cup=new CupImplements2();
        cup.identity();
        Glass glass=new CupImplements2();
        glass.identity();
        Door door=new DoorImplements2();
        door.state();
        Window window=new DoorImplements2();
        window.state();
        Wall wall=new WallImplements2();
        wall.behaviour();
        Roof roof=new WallImplements2();
        roof.identity();
        Floor floor=new FloorImplements2();
        floor.state();
        Key key=new FloorImplements2();
        key.state();
        Lock lock=new LockImplements2();
        lock.behaviour();
        Bag bag=new LockImplements2();
        bag.behaviour();
        Shirt shirt=new ShirtImplements2();
        shirt.identity();
        Pant pant=new ShirtImplements2();
        pant.identity();
        Shoe shoe=new ShoeImplements2();
        shoe.state();
        Socks socks=new ShoeImplements2();
        socks.state();
        Cap cap=new CapImplements2();
        cap.behaviour();
        Helmet helmet=new CapImplements2();
        helmet.behaviour();
        Pillow pillow=new PillowImplements2();
        pillow.identity();
        Blanket blanket=new PillowImplements2();
        blanket.identity();
        Bed bed=new BedImplements2();
        bed.state();
        Sofa sofa=new BedImplements2();
        sofa.state();
        Carpet carpet=new CarpetImplements2();
        carpet.behaviour();
        Mirror mirror=new CarpetImplements2();
        mirror.behaviour();
    }
}
